### PR TITLE
Reviewed relationships

### PR DESCRIPTION
**Pull request by ggam**
@bshannon could you please review the changed relationships?

Basically:
- CDI now requires Interceptors and EL
- JSF requires Expression Language, JSP and JSTL
- GlassFish implements JAXR
- Stable APIs implements the JAX-RPC RI

### CODE REVIEW

**Comment by bshannon** [comment]
Red Hat should answer about CDI but the rest are correct.

**Comment by ggam** [comment]
Thanks Bill. @antoine_sd could you please confirm CDI requires Interceptors and Expression Language and no other (mandatory) Java EE specs? Thanks!

**Comment by ggam** [comment]
Sorry, @antoinesd.

**Comment by m0mus** [comment]
This PR is outdated as we discussed it by email. Closing it.

**Pull request closed without merging**
