### PR TITLE
Specs diagram

### PR DESCRIPTION
**Pull request by ggam**
Preview: https://cdn.rawgit.com/ggam/ee4j-website/spec-relationships/generated/images/specs.svg

This is a spec only diagram, showing requirements and integration between specs. There will be errors and omissions as I took lot of information just by searching from Maven POM dependents, and others by looking at the spec. The "integrates with" relationship also means "uses".

The resulting image is very complex but could be pretty useful for people to understand the relationships.

I left some TODO comments on the .dot file. Some questions:
- @bshannon: I have some serious doubts on the JAXB, JAXWS, JAXR, etc relationships. Could you please review it?
- @arjantijms: is JACC specifically mentioned on some spec apart from the umbrella platform?
- @dblevins: I think you know JCA well. Who defines the EJB-JCA integration? EJB integrates with JCA, or the opposite? Also, is JCA really integrated with CDI? Do its artifacts at least support `@Inject`?

### CODE REVIEW

**Comment by arjantijms** [comment]
@ggam 

Wow, pretty cool!

JACC effectively extends both the Servlet and EJB specifications, by more specifically specifying what these two specs implicitly already have to do, which is among others collecting and storing security constraints (web.xml, ejb-jar.xml and annotations) and making the authorisation decisions based on them.

JACC does something very similar for Servlet and JAX-RPC/JAX-WS (SOAP). It extends those specifications by standardising something that they already do, which is calling an authentication mechanism.

In that respect those are both a little different than other specs. JSF for instances uses Servlet (builds on top of it), but JASPIC and JACC sort of inject behaviour into other specs. I.e. its like they add a new chapter or appendix to those specs.

Hope this helps ;)

**Comment by bshannon** [comment]
Very nice!

I would remove the Jakarta EE platform links because they don't help anything; the entire page is the platform.

Once JAXB and JAX-WS moved into the JDK, we stopped worrying about the dependencies so much.  Some of the current hard dependencies we had hoped to turn into optional dependencies.

I don't know if the JAXR spec requires it, but the expectation is that a JAXR provider implementation will be supplied as a JCA resource adapter.  Maybe that should be an "integrates with" dependency?

I think JWS effectively depends on JAX-WS.

**Comment by ggam** [comment]
@arjantijms thanks. My question then is who is the owner of the
relationship. From a spec point of view it's clear JACC integrates with
EJB, since it's JACC who defines the relationship. But in practice, it's
EJB who has to call JACC code. So I think it's fair to say that:
- EJB and Servlet integrate with JACC
- JAX-WS, JAX-RPC and Serlvet integrate with JASPIC.

In the same way, EJB defines message driven beans and mandate a JMS
provider to be present and work with them. But then again, JMS defines some
properties to work with EJB. Is that a bidirectional relationship, or is it
really EJB who integrates with JMS? For me it's the second

@bshannon you're right, the Jakarta EE node is of little value there. I'll
remove it this afternoon.

I've checked the JAXR spec and it doesn't mention JCA. GlassFish seems to
bundle it as a resource adapter, but I think IBM or RedHat use custom
implementations (I haven't found related information for WebLogic). Perhaps
we could anyway define the relationship and also on JavaMail, which is also
often implemented as a resource adapter, without the spec mentioning it.

At least on its POM, JAX-WS depends on JWS instead of the other way around:
http://mvnrepository.com/artifact/javax.jws/jsr181-api/usages

Could you please ask someone from Oracle to review those XML spec
relationships? I could have a deeper look at the specs myself, but I think
it's better if we find someone from the field.

**Comment by ggam** [comment]
I just made the following changes:
- EJB integrates with JACC
- JAX-WS integrates with JASPIC
- JAX-WS requires JWS
- JAX-RPC integrates with JASPIC, Servlet and EJB
- Servlet integrates with JACC
- JMS integrates with JCA
- JavaMail integrates with JCA
- JAXR integrates with JCA
- JSF requires WebSocket and Servlet
- JPA integrates with JTA

**Comment by ivargrimstad** [comment]
@waynebeaton Is this one good to merge?

**Comment by m0mus** [comment]
Please resolve conflicts.

**Comment by ggam** [comment]
Conflicts fixed. The generated folder should probably be `.gitignored`, but it was already there so I think another PR to address it is better.

**Pull request merged**
