### PR TITLE
Add Minutes for Meeting 11 (2018-04-10)

### PR DESCRIPTION
**Pull request by ivargrimstad**

### CODE REVIEW

**Comment by ivargrimstad** [comment]
@waynebeaton: This time, I will do the merge and push to EF server to verify that the access is ok, so review is all I need  from you this time :)

**Review by smillidge — APPROVED** [review]

**Review by kwsutter — APPROVED** [review]
LGTM; Thanks, Ivar!

**Comment by waynebeaton** [comment]
+1

**Review by m0mus — APPROVED** [review]
LGTM

**Pull request merged**
