### PR TITLE
Correct JSR-181 and add JSR-109.

### PR DESCRIPTION
**Pull request by bshannon**

### CODE REVIEW

**Comment by bshannon** [comment]
*&^#$^@#($%#(^%&*#!!!!!

It's going to take me awhile to remember to use "git commit -s".
When I forget to do that, what's the right way to go back and
add the Signed-Off-By comment so that ip-validation will pass?

**Comment by m0mus** [comment]
@bshannon `git commit --amend --signoff` followed by `git push --force`

**Comment by bshannon** [comment]
Ah ha!  --force is the secret!  I tried --amend --signoff, but that wasn't enough.
Thanks, Dmitry!

**Comment by m0mus** [comment]
I see that this PR duplicates this one https://github.com/eclipse-ee4j/ee4j-website/pull/26
Does it makes sense to close it merge another one?

**Pull request closed without merging**
